[project @ 119] Updated template sync scripts with extra commands.

diff --git a/project/sync b/project/sync
--- a/project/sync
+++ b/project/sync
@@ -1,26 +1,71 @@
 #!/bin/sh
 
-# Make sure that we're in the right directory.
-HERE=`dirname $0`
+do_sync () {
+	local OLD_LOC=`pwd`
+	echo Syncing from ./$1 to $2/$1...
+	cd $1
+	rsync -rlptvz --delete --exclude="sync" --exclude="*~" --exclude=".htaccess" --exclude=".svn" --exclude=".*.sw?" --rsh=/usr/bin/ssh ./ "$2/$1"
+	cd $OLD_LOC
+}
 
-# Details for syncing with the live site.
-REMOTE="%%USER%%@%%SERVER%%:%%APPLICATION_PATH%%"
+do_sync_all () {
+	echo "Affirmative, Dave, I read you."
+	for AREA in .; do
+		do_sync $AREA "$1"
+	done
+}
 
-if [ "$1" = "lint" ]; then
-	echo "Please wait, checking PHP code in project for syntax errors..."
-	for i in `find $HERE -name \*.php`; do
-		if ! php -l "$i" >/dev/null; then
-			exit 255
+do_lint () {
+	local i=''
+
+	for i in `find . -name \*.php`; do
+		if ! php -l "$i"; then
+			echo $i has errors.
+			return $?
 		fi
 	done
-	echo "PHP code successfully linted."
-	exit 0
-fi
 
-echo "You'll need to edit me before you even think about running me."
-exit 255
+	for i in `find . -name \*.inc`; do
+		if ! php -l "$i"; then
+			echo $i has errors.
+			return $?
+		fi
+	done
 
-/usr/bin/rsync -rlptvz --delete --rsh=/usr/bin/ssh \
-	--exclude="sync" --exclude="*~" --exclude=".htaccess" --exclude=".svn" \
-	--exclude=".*.sw?" --exclude="tests" \
-	$HERE/ $REMOTE
+	return 0
+}
+
+# Make sure that we're in the right directory.
+cd `dirname $0`
+
+case "$1" in
+	lint)
+	if do_lint; then
+		echo All clean!
+	fi
+	;;
+
+	purge-svn)
+	echo Purging .svn directories...
+	find . -name .svn -type d -exec rm -rf {} +
+	echo Done!
+	;;
+
+	production)
+	# Remove these three lines, and possibly edit the do_sync_all function.
+	echo "You'll need to edit me before you even think about running me."
+	exit 255
+	do_sync_all "%%PROD_USER%%@%%PROD_SERVER%%:%%PROD_APPLICATION_PATH%%"
+	;;
+
+	test)
+	# Remove these three lines, and possibly edit the do_sync_all function.
+	echo "You'll need to edit me before you even think about running me."
+	exit 255
+	do_sync_all "%%TEST_USER%%@%%TEST_SERVER%%:%%TEST_APPLICATION_PATH%%"
+	;;
+
+	*)
+	echo "I'm sorry Dave, I'm afraid I can't do that."
+	exit 1
+esac
